server:
  port: 8084
spring:
  application:
    name: studyParty-websocket
  cloud:
    nacos:
      username: nacos
      password: nacos
      config:
        server-addr: nacos:8848
      discovery:
        enabled: true
        namespace: 086bcf84-a9bb-4265-aa7c-98fcad205276
        server-addr: nacos:8848
  data:
    redis:
      port: 6379
      timeout: 6000 # 连接超时时间
      host: redis
  kafka:
    bootstrap-servers: kafka:9092 # Kafka服务器地址
    consumer:
      group-id: studyParty # 消费组ID
      auto-offset-reset: earliest # 当没有初始偏移量时该做何处理（earliest, latest）
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  webflux:
    static-path-pattern: /** # 静态资源路径模式
  web:
    resources:
      static-locations: classpath:/static/,file:./uploads/

springdoc:
  api-docs:
    path: /v3/api-docs  # API文档路径
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.studyParty.websocket.controller  # 扫描Controller包
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
# application.yml示例
dubbo:
  application:
    name: studyParty-websocket # 应用名称
  registry:
    address: nacos://nacos:8848?username=nacos&password=nacos&namespace=086bcf84-a9bb-4265-aa7c-98fcad205276 # 注册中心地址
  config-center:
    address: nacos://nacos:8848?username=nacos&password=nacos&namespace=086bcf84-a9bb-4265-aa7c-98fcad205276 # 配置中心地址
  protocol:
    name: dubbo
    port: 20880 # 服务暴露端口
  scan:
    base-packages: com.studyParty.dubboApi.service # 扫描服务接口所在包
# 服务提供方
dubbo.provider:
  timeout: 2000 # 服务提供方超时时间
# 服务消费方
dubbo.consumer:
  timeout: 2000 # 服务消费方超时时间

knife4j:
  enable: true
  setting:
    language: zh_cn
logging:
  level:
    com.studyParty.websocket: DEBUG
    org.springframework.web.reactive.socket: DEBUG
    reactor.netty: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
# WebSocket配置
websocket:
  endpoint: /ws # WebSocket端点路径
  allowed-origins: "*" # 允许的跨域来源
# 文件上传配置
file:
  upload-dir: /root/studyParty/websocket/