version: '3.8'

services:
  # 网关服务 - 首先启动
  gateway:
    build: 
      context: ./studyParty_.gateway
    container_name: study-party-gateway
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - NACOS_SERVER_ADDR=nacos:8848
    networks:
      - studyparty-network
    depends_on:
      - nacos

  # Dubbo服务 - 第二个启动
  dubbo-api:
    build:
      context: ./studyParty_dubboApi
    container_name: study-party-dubbo-api
    ports:
      - "8090:8090"
      - "20880:20880"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - NACOS_SERVER_ADDR=nacos:8848
    networks:
      - studyparty-network
    depends_on:
      - nacos

  # 用户服务
  user-service:
    build:
      context: ./studyParty_user
    container_name: study-party-user
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - NACOS_SERVER_ADDR=nacos:8848
    networks:
      - studyparty-network
    depends_on:
      - gateway
      - dubbo-api
      - nacos

  # 文章服务
  article-service:
    build:
      context: ./studyParty_article
    container_name: study-party-article
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - NACOS_SERVER_ADDR=nacos:8848
    networks:
      - studyparty-network
    depends_on:
      - gateway
      - dubbo-api
      - nacos

  # 群组服务
  group-service:
    build:
      context: ./studyParty_group
    container_name: study-party-group
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - NACOS_SERVER_ADDR=nacos:8848
    networks:
      - studyparty-network
    depends_on:
      - gateway
      - dubbo-api
      - nacos

  # websocket服务
  websocket-service:
    build:
      context: ./studyParty_websocket
    container_name: study-party-websocket
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - NACOS_SERVER_ADDR=nacos:8848
    networks:
      - studyparty-network
    depends_on:
      - gateway
      - dubbo-api
      - nacos

  # AI服务
  ai-service:
    build:
      context: ./studyParty_AI
    container_name: study-party-ai
    ports:
      - "8086:8086"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - NACOS_SERVER_ADDR=nacos:8848
    networks:
      - studyparty-network
    depends_on:
      - gateway
      - dubbo-api
      - nacos

  # Nacos 服务（从docker-compose-env.yml中引入）
  nacos:
    extends:
      file: docker-compose-env.yml
      service: nacos
    networks:
      - studyparty-network

  # Redis 服务（从docker-compose-env.yml中引入）
  redis:
    extends:
      file: docker-compose-env.yml
      service: redis
    networks:
      - studyparty-network

  # Kafka 服务（从docker-compose-env.yml中引入）
  zookeeper:
    extends:
      file: docker-compose-env.yml
      service: zookeeper
    networks:
      - studyparty-network

  kafka:
    extends:
      file: docker-compose-env.yml
      service: kafka
    networks:
      - studyparty-network

networks:
  studyparty-network:
    driver: bridge