server:
  port: 8080
spring:
  servlet:
    multipart:
      max-file-size: 10MB      # 单个文件最大大小
      max-request-size: 10MB   # 整个请求最大大小
  codec:
    max-in-memory-size: 10MB
  application:
    name: studyParty-gateway
  cloud:
    nacos:
      config:
        namespace: 086bcf84-a9bb-4265-aa7c-98fcad205276
      discovery:
        username: nacos
        password: nacos
        server-addr: localhost:8848
        namespace: 086bcf84-a9bb-4265-aa7c-98fcad205276
        enabled: true
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true  # 解决 OPTIONS 请求被拦截
        cors-configurations:
          '[/**]': # 匹配所有路径
            allowed-origin-patterns: "*"  # 使用origin patterns替代allowed-origins
            allowed-methods: # 允许的 HTTP 方法
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowed-headers: "*"  # 允许所有请求头
            allow-credentials: true  # 是否允许携带 Cookie
            max-age: 3600  # 预检请求缓存时间（秒）
      httpclient:
        max-initial-line-length: 8192
        max-header-size: 8192
        max-chunk-size: 16384
        ssl:
          use-insecure-trust-manager: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: openapi-route   # 确保存在此路由
          uri: no://op
          predicates:
           - Path=/v3/api-docs/**  # 关键路径匹配

        - id: userServiceRoute
          uri: lb://studyParty-user
          predicates:
            - Path=/user/**, /studyParty-user/**
          filters:
            - StripPrefix=1
        - id: websocket
          uri: lb://studyParty-websocket
          predicates:
            - Path=/websocket/**, /studyParty-websocket/**
          filters:
            - StripPrefix=1

        -  id: groupServiceRoute
           uri: lb://studyParty-group
           predicates:
            - Path=/group/**, /studyParty-group/**
           filters:
            -  StripPrefix=1
        - id: articleServiceRoute
          uri: lb://studyParty-article
          predicates:
            - Path=/article/**, /studyParty-article/**
          filters:
            - StripPrefix=1

        - id: dubboApiRoute
          uri: lb://studyParty-dubboApi
          predicates:
            - Path=/dubboApi/**, /studyParty-dubboApi/**
          filters:
            - StripPrefix=1

        - id: resources
          uri: lb://studyParty-resources
          predicates:
            - Path=/resources/**
          filters:
            - StripPrefix=1

        - id: knife4j-ui
          uri: no://op
          predicates:
            - Path=/doc.html
            - Path=/webjars/**
            - Path=/swagger-resources/**
  data:
    redis:
      port: 6379
      timeout: 6000 # 可选，默认单位为毫秒
      host: localhost
knife4j:
  gateway:
    enabled: true
    strategy: discover  # 自动发现注册中心的服务
    discover:
      enabled: true
      version: openapi3  # 使用OpenAPI 3.0
logging:
  level:
    com.alibaba.nacos: DEBUG
gateway:
  static-resource:
    local-dir: D://studyParty/
    image-path: /images