server:
  port: 8080

spring:
  application:
    name: studyParty-gateway
  cloud:
    nacos:
      config:
        namespace: 086bcf84-a9bb-4265-aa7c-98fcad205276
      discovery:
        username: nacos
        password: nacos
        server-addr: localhost:8848
        namespace: 086bcf84-a9bb-4265-aa7c-98fcad205276
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: openapi-route   # 确保存在此路由
          uri: no://op
          predicates:
           - Path=/v3/api-docs/**  # 关键路径匹配
        - id: userServiceRoute
          uri: lb://studyParty-user
          predicates:
            - Path=/user/**, /studyParty-user/**
          filters:
            - StripPrefix=1
        -  id: groupServiceRoute
           uri: lb://studyParty-group
           predicates:
            - Path=/group/**, /studyParty-group/**
           filters:
            -  StripPrefix=1

        - id: resources
          uri: lb://studyParty-resources
          predicates:
            - Path=/resources/**
          filters:
            - StripPrefix=1

        - id: knife4j-ui
          uri: no://op
          predicates:
            - Path=/doc.html
            - Path=/webjars/**
            - Path=/swagger-resources/**
  data:
    redis:
      port: 6379
      timeout: 6000 # 可选，默认单位为毫秒
      host: localhost
knife4j:
  gateway:
    enabled: true
    strategy: discover  # 自动发现注册中心的服务
    discover:
      enabled: true
      version: openapi3  # 使用OpenAPI 3.0
logging:
  level:
    com.alibaba.nacos: DEBUG
gateway:
  static-resource:
    local-dir: D://studyParty/
    image-path: /images