server:
  port: 8090
spring:
  application:
    name: studyParty-dubboApi
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://studyparty.pg.polardb.rds.aliyuncs.com:5432/studyparty?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&currentSchema=public
    username: root_yzt
    password: Yzt9345245374
  cloud:
    nacos:
      username: nacos
      password: nacos
      config:
        server-addr: nacos://nacos:8848?username=nacos&password=nacos&namespace=086bcf84-a9bb-4265-aa7c-98fcad205276
      discovery:
        enabled: false
        namespace: 086bcf84-a9bb-4265-aa7c-98fcad205276
        server-addr: nacos://nacos:8848?username=nacos&password=nacos&namespace=086bcf84-a9bb-4265-aa7c-98fcad205276
  data:
    redis:
      port: 6379
      timeout: 6000 # ??????????
      host: redis
  kafka:
    bootstrap-servers: kafka:9092 # Kafka服务器地址
    consumer:
      group-id: studyParty # 消费组ID
      auto-offset-reset: earliest # 当没有初始偏移量时该做何处理（earliest, latest）
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
mybatis-plus:
  type-aliases-package: com.studyParty.entity.*
  mapper-locations: classpath:Mapper/**/*.xml
  configuration:
    # 关闭自动转义关键字（防止生成反引号）
    auto-mapping-behavior: FULL
    map-underscore-to-camel-case: true
    # ️ 关键：禁止 MyBatis 自动加反引号
    # PostgreSQL 不支持反引号，必须关闭标识符自动转义
    safe-row-bounds-enabled: true

# application.yml示例

dubbo:
  application:
    name: studyParty-dubboApi # 应用名称
  registry:
    address: nacos://nacos:8848?username=nacos&password=nacos&namespace=086bcf84-a9bb-4265-aa7c-98fcad205276 # 注册中心地址
  config-center:
    address: nacos://nacos:8848?username=nacos&password=nacos&namespace=086bcf84-a9bb-4265-aa7c-98fcad205276 # 配置中心地址
  protocol:
    name: dubbo
    port: 20880 # 服务暴露端口
  scan:
    base-packages: com.studyParty.dubboApi.service # 扫描服务接口所在包
# 服务提供方
dubbo.provider:
  timeout: 2000 # 服务提供方超时时间
# 服务消费方
dubbo.consumer:
  timeout: 2000 # 服务消费方超时时间
knife4j:
  enable: false
head: static/head/
saveHead: /root/studyParty/head/