server:
  port: 8083
spring:
  application:
    name: studyParty-group
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/studyparty?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 9345245374
  cloud:
    nacos:
      username: nacos
      password: nacos
      config:
        server-addr: localhost:8848
      discovery:
        namespace: 086bcf84-a9bb-4265-aa7c-98fcad205276
        server-addr: localhost:8848
  data:
    redis:
      port: 6379
      timeout: 6000 # ??????????
      host: localhost
mybatis-plus:
  type-aliases-package: com.studyParty.group.domain
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
springdoc:
  api-docs:
    path: /v3/api-docs  # ??????????????
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.studyParty.group.controller  # ??????Controller?
  swagger-ui:
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config

knife4j:
  enable: true  # ??Knife4j??UI
  setting:
    language: zh_cn